### ISSUE TITLE
Can not resolve any host with latest image

### ISSUE THREAD

**Issue by P-Verbrugge** [bubuntux/nordlynx#53]
### **Describe the bug**
Updated the old container to the newest by rebuilding it through portainer and pulling the latest image.

version: '3'
services:
  vpn:
    image: bubuntux/nordlynx
```

### **Expected behavior**
When I do curl ifconfig.me I would expect an ip to return. When I do a ping to a website, I would expect it to show the ping. In all cases I get a "Can not resolve host".

### **Logs**
There are no errors. The logs says I am connected correctly.

### **Additional context**
It's something in the latest image. I have the previous version running, before the last update, on a different machine and there it still works.

**Comment by P-Verbrugge** [comment]
Nevermind. Missed the part, that you have to set a DNS yourself now.

**Comment by michaelkrieger** [comment]
> Nevermind. Missed the part, that you have to set a DNS yourself now.

I still don't think that's explicit anywhere in the docs. It certainly isn't in the examples in the readme.

So not setting DNS allows you to internally resolve other containers connected to the VPN. Generally those containers connected to the VPN network rarely access other services.

Setting DNS allows you to resolve the millions of servers on the Internet. This decision is frankly very wrong. DNS should be defaulting to the [NordVPN servers](https://support.nordvpn.com/Connectivity/Linux/1134945702/Change-your-DNS-servers-on-Linux.htm) of 103.86.96.100,103.86,99,100 or at the very least cloudflare (1.1.1.1) or Google (8.8.8.8,8.8.4.4) if unset...  rather than simply not resolving anything.

Setting this to NordVPN's servers and then having a note that you lose the ability to resolve others is key.
