### ISSUE TITLE
Add support of parameter 'CONNECT'

### ISSUE THREAD

**Issue by treker** [bubuntux/nordlynx#57]
**Is your feature request related to a problem? Please describe.**
I would like to connect VPN to specific country or server.

**Describe the solution you'd like**
Please add the functionality of parameter 'CONNECT' as what you provided in https://github.com/bubuntux/nordvpn

**Comment by Kruk79** [comment]
Instead of CONNECT you have to use the QUERY parameter but with the syntax used for the NordVPN API. Check the Environment table on the main page.

Query can be used as:

QUERY=filters\[country_id\]=153 #Netherlands

Please see Discussion tab for info re servers and IDs: [https://github.com/bubuntux/nordlynx/discussions/8](url)

All this can be found in Discussion section.
